MODULE egs_tho_f
  !
  USE nrtype
  !
  IMPLICIT NONE
  !
  !
  ! NDX -> XGRID DIMENSION
  INTEGER(KIND = I4B) :: dim_X
  ! HARDIM -> DIMENSION OF THE HO BASIS
  INTEGER(KIND = I4B) :: dim_THO
  ! XGRID
  REAL(KIND = DP), DIMENSION(:), ALLOCATABLE :: X_Grid 
  REAL(KIND = DP) :: X_min, X_max, Delta_X
  !     
  ! HARMONIC BASIS, EIGENVALUES AND EIGENVECTORS
  REAL(KIND = DP),  DIMENSION(:), ALLOCATABLE :: Aval_THO
  REAL(KIND = DP),  DIMENSION(:,:), ALLOCATABLE ::  THO_Bas, Avec_THO, Avec_THO_X
  ! EIGENVECTOR DERIVATIVES
  REAL(KIND = DP), DIMENSION(:,:), ALLOCATABLE :: Avec_THO_Der_X
  !
  !
END MODULE egs_tho_f
