BINPATH = ../bin/
#
#     HO
1body_1D_HO_wsaxon_SRC = nrtype.f90 constants.f90 pot_param.f90	egs_mod_ho.f90 \
ho_1body_1D.f90 build_HO_bas.f90 ham_mat_1D_1body_ho.f90 \
wsaxon_pot.f90 e_gstate_ho.f90 e1.f90 e2.f90 \
wfp_ho.f90 total_strength.f90 ew_sum_rule.f90 \
phase_shift_HT.f90 phase_shift_CH.f90 
#
1body_1D_HO_wsaxon_OBJ = $(1body_1D_HO_wsaxon_SRC:.f90=.o)
#
1body_1D_HO_mexhat_SRC = nrtype.f90 constants.f90 pot_param.f90	egs_mod_ho.f90 \
ho_1body_1D.f90 build_HO_bas.f90 ham_mat_1D_1body_ho.f90 \
mexican_hat_pot.f90 e_gstate_ho.f90 e1.f90 e2.f90 \
wfp_ho.f90 total_strength.f90 ew_sum_rule.f90 \
phase_shift_HT.f90 phase_shift_CH.f90 
#
1body_1D_HO_mexhat_OBJ = $(1body_1D_HO_mexhat_SRC:.f90=.o)
#
1body_1D_HO_barrierws_SRC = nrtype.f90 constants.f90 pot_param.f90	egs_mod_ho.f90 \
ho_1body_1D.f90 build_HO_bas.f90 ham_mat_1D_1body_ho.f90 \
barrierws_pot.f90 e_gstate_ho.f90 e1.f90 e2.f90 \
wfp_ho.f90 total_strength.f90 ew_sum_rule.f90 \
phase_shift_HT.f90 phase_shift_CH.f90 
#
1body_1D_HO_barrierws_OBJ = $(1body_1D_HO_barrierws_SRC:.f90=.o)
#
1body_1D_HO_ht_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_ho.f90 \
ho_1body_1D.f90 build_HO_bas.f90 ham_mat_1D_1body_ho.f90 \
hazitaylor_pot.f90 e_gstate_ho.f90 e1.f90 e2.f90 \
wfp_ho.f90 total_strength.f90 ew_sum_rule.f90 \
phase_shift_HT.f90 phase_shift_CH.f90 
#
1body_1D_HO_ht_OBJ = $(1body_1D_HO_ht_SRC:.f90=.o)
#
1body_1D_HO_pteller_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_ho.f90 \
ho_1body_1D.f90 build_HO_bas.f90 ham_mat_1D_1body_ho.f90 e_gstate_ho.f90 \
pteller_pot.f90 wfp_ho.f90 total_strength.f90 ew_sum_rule.f90 \
e1.f90 e2.f90 phase_shift_HT.f90 phase_shift_CH.f90 
#
1body_1D_HO_pteller_OBJ = $(1body_1D_HO_pteller_SRC:.f90=.o)
#
1body_1D_HO_morse_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_ho.f90 \
ho_1body_1D.f90 build_HO_bas.f90 ham_mat_1D_1body_ho.f90 e_gstate_ho.f90 \
morse_pot.f90 wfp_ho.f90 total_strength.f90 ew_sum_rule.f90 \
e1.f90 e2.f90 phase_shift_HT.f90 phase_shift_CH.f90 
#
1body_1D_HO_morse_OBJ = $(1body_1D_HO_morse_SRC:.f90=.o)
#
1body_1D_HO_ginocchio_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_ho.f90 \
ho_1body_1D.f90 build_HO_bas.f90 ham_mat_1D_1body_ho.f90 e_gstate_ho.f90 \
ginocchio_pot.f90 wfp_ho.f90 total_strength.f90 ew_sum_rule.f90 \
e1.f90 e2.f90 phase_shift_HT.f90 phase_shift_CH.f90 
#
1body_1D_HO_ginocchio_OBJ = $(1body_1D_HO_ginocchio_SRC:.f90=.o)
#
#
#     THO
1body_1D_THO_wsaxon_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_tho.f90 lst_param.f90 \
tho_1body_1D.f90 build_THO_bas.f90 ham_mat_1D_1body_tho.f90 e_gstate_tho.f90 \
wsaxon_pot.f90 wfp_tho.f90 total_strength.f90 ew_sum_rule.f90 \
e1.f90 e2.f90 phase_shift_HT.f90
#
1body_1D_THO_wsaxon_OBJ = $(1body_1D_THO_wsaxon_SRC:.f90=.o)
#
1body_1D_THO_barrierws_SRC = nrtype.f90 constants.f90 pot_param.f90 lst_param.f90 egs_mod_tho.f90 \
tho_1body_1D.f90 build_THO_bas.f90 ham_mat_1D_1body_tho.f90 e_gstate_tho.f90 \
barrierws_pot.f90 e1.f90 e2.f90 \
wfp_tho.f90 total_strength.f90 ew_sum_rule.f90 \
phase_shift_HT.f90  
#
1body_1D_THO_barrierws_OBJ = $(1body_1D_THO_barrierws_SRC:.f90=.o)
#
1body_1D_THO_ht_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_tho.f90 lst_param.f90 \
tho_1body_1D.f90 build_THO_bas.f90 ham_mat_1D_1body_tho.f90 \
hazitaylor_pot.f90 e_gstate_tho.f90 e1.f90 e2.f90 \
wfp_tho.f90 total_strength.f90 ew_sum_rule.f90 \
phase_shift_HT.f90 
#
1body_1D_THO_ht_OBJ = $(1body_1D_THO_ht_SRC:.f90=.o)
#
1body_1D_THO_pteller_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_tho.f90 lst_param.f90 \
tho_1body_1D.f90 build_THO_bas.f90 ham_mat_1D_1body_tho.f90 e_gstate_tho.f90 \
pteller_pot.f90 wfp_tho.f90 total_strength.f90 ew_sum_rule.f90 \
e1.f90 e2.f90 phase_shift_HT.f90
#
1body_1D_THO_pteller_OBJ = $(1body_1D_THO_pteller_SRC:.f90=.o)
#
1body_1D_THO_morse_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_tho.f90 lst_param.f90 \
tho_1body_1D.f90 build_THO_bas.f90 ham_mat_1D_1body_tho.f90 e_gstate_tho.f90 \
morse_pot.f90 wfp_tho.f90 total_strength.f90 ew_sum_rule.f90 \
e1.f90 e2.f90 phase_shift_HT.f90
#
1body_1D_THO_morse_OBJ = $(1body_1D_THO_morse_SRC:.f90=.o)
#
1body_1D_THO_ginocchio_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_tho.f90 lst_param.f90 \
tho_1body_1D.f90 build_THO_bas.f90 ham_mat_1D_1body_tho.f90 e_gstate_tho.f90 \
ginocchio_pot.f90 wfp_tho.f90 total_strength.f90 ew_sum_rule.f90 \
e1.f90 e2.f90 phase_shift_HT.f90
#
1body_1D_THO_ginocchio_OBJ = $(1body_1D_THO_ginocchio_SRC:.f90=.o)
#
#
#     ISQW
1body_1D_ISQW_wsaxon_SRC = nrtype.f90 constants.f90 pot_param.f90 \
egs_mod_isqw.f90 infsq_box_1D.f90 build_ISQW_bas.f90 ham_mat_1D_1body_isqw.f90 \
e1.f90 e2.f90 ew_sum_rule.f90 total_strength.f90 wsaxon_pot.f90 \
phase_shift_HT.f90
#
1body_1D_ISQW_wsaxon_OBJ = $(1body_1D_ISQW_wsaxon_SRC:.f90=.o)
#
1body_1D_ISQW_ht_SRC = nrtype.f90 constants.f90 pot_param.f90 \
egs_mod_isqw.f90 infsq_box_1D.f90 build_ISQW_bas.f90 ham_mat_1D_1body_isqw.f90 \
e1.f90 e2.f90 ew_sum_rule.f90 total_strength.f90 hazitaylor_pot.f90 \
phase_shift_HT.f90
#
1body_1D_ISQW_ht_OBJ = $(1body_1D_ISQW_ht_SRC:.f90=.o)
#
1body_1D_ISQW_pteller_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_isqw.f90 \
infsq_box_1D.f90 build_ISQW_bas.f90 ham_mat_1D_1body_isqw.f90 \
pteller_pot.f90  total_strength.f90 ew_sum_rule.f90 \
e1.f90 e2.f90 phase_shift_HT.f90
#
1body_1D_ISQW_pteller_OBJ = $(1body_1D_ISQW_pteller_SRC:.f90=.o)
#
1body_1D_ISQW_morse_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_isqw.f90 \
infsq_box_1D.f90 build_ISQW_bas.f90 ham_mat_1D_1body_isqw.f90 \
morse_pot.f90  total_strength.f90 ew_sum_rule.f90 \
e1.f90 e2.f90 phase_shift_HT.f90
#
1body_1D_ISQW_morse_OBJ = $(1body_1D_ISQW_morse_SRC:.f90=.o)
#
1body_1D_ISQW_ginocchio_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_isqw.f90 \
infsq_box_1D.f90 build_ISQW_bas.f90 ham_mat_1D_1body_isqw.f90 \
ginocchio_pot.f90  total_strength.f90 ew_sum_rule.f90 \
e1.f90 e2.f90 phase_shift_HT.f90
#
1body_1D_ISQW_ginocchio_OBJ = $(1body_1D_ISQW_ginocchio_SRC:.f90=.o)
#
#
#      ANALYTICAL B1 AND B2 INTEGRATION
#
B1_B2_INTEGRAL_OBJ = $(B1_B2_INTEGRAL_SRC:.f90=.o)
#
B1_B2_INTEGRAL_SRC = nrtype.f90\
analytical_B1_B2.f90\
#
B1_B2_INTEGRAL_OBJ = $(B1_B2_INTEGRAL_SRC:.f90=.o)
#
#
#
FC = gfortran
FOPT	= -c 
FOPT   += -Wall
MODLIB   = -I/usr/local/lib/lapack95/lapack95_modules
MODLIB   += -I/usr/local/include/lapack95_modules
FOPT   += $(MODLIB)
#
LAPACK95_PATH =	 /usr/local/lib
LAPACK95 = $(LAPACK95_PATH)/lapack95.a
# Cluster
LAPACK77 = -llapack
BLAS     = -lblas
# NAG
NAGLIB = -L/usr/local/lib/NAG -lnag
#
LIBS     = $(NAGLIB) $(LAPACK95) $(LAPACK77) $(BLAS)

all: HO THO ISQW ANALYTICAL_B1B2
HO: wsaxon_HO_1body_1D mexhat_HO_1body_1D barrierws_HO_1body_1D  ht_HO_1body_1D pteller_HO_1body_1D  morse_HO_1body_1D  ginocchio_HO_1body_1D
THO: wsaxon_THO_1body_1D  barrierws_THO_1body_1D  ht_THO_1body_1D pteller_THO_1body_1D morse_THO_1body_1D ginocchio_THO_1body_1D
ISQW: wsaxon_ISQW_1body_1D ht_ISQW_1body_1D pteller_ISQW_1body_1D morse_ISQW_1body_1D ginocchio_ISQW_1body_1D
ANALYTICAL_B1B2: B1_B2_INTEGRAL
.PHONY : all
# 
#
# Standard compilation rules
#
%.o: %.f90
	$(FC) $(FOPT) -c $<
#
%.o: %.F90
	$(FC) $(FOPT) -c $<
#
%.o: %.f
	$(FC) $(FOPT) $<
#
#######################
wsaxon_HO_1body_1D: $(1body_1D_HO_wsaxon_OBJ)
	$(FC) -o $(BINPATH)/wsaxon_1body_1D_HO  $(1body_1D_HO_wsaxon_OBJ) $(LIBS) 
mexhat_HO_1body_1D: $(1body_1D_HO_mexhat_OBJ)
	$(FC) -o $(BINPATH)/mexhat_1body_1D_HO  $(1body_1D_HO_mexhat_OBJ) $(LIBS) 
barrierws_HO_1body_1D: $(1body_1D_HO_barrierws_OBJ)
	$(FC) -o $(BINPATH)/barrierws_1body_1D_HO  $(1body_1D_HO_barrierws_OBJ) $(LIBS) 
ht_HO_1body_1D: $(1body_1D_HO_ht_OBJ)
	$(FC) -o $(BINPATH)/ht_1body_1D_HO  $(1body_1D_HO_ht_OBJ) $(LIBS) 
pteller_HO_1body_1D: $(1body_1D_HO_pteller_OBJ)
	$(FC) -o $(BINPATH)/pteller_1body_1D_HO  $(1body_1D_HO_pteller_OBJ) $(LIBS) 
morse_HO_1body_1D: $(1body_1D_HO_morse_OBJ)
	$(FC) -o $(BINPATH)/morse_1body_1D_HO  $(1body_1D_HO_morse_OBJ) $(LIBS) 
ginocchio_HO_1body_1D: $(1body_1D_HO_ginocchio_OBJ)
	$(FC) -o $(BINPATH)/ginocchio_1body_1D_HO  $(1body_1D_HO_ginocchio_OBJ) $(LIBS) 
#######################
#######################
wsaxon_THO_1body_1D: $(1body_1D_THO_wsaxon_OBJ)
	$(FC) -o $(BINPATH)/wsaxon_1body_1D_THO  $(1body_1D_THO_wsaxon_OBJ) $(LIBS) 
barrierws_THO_1body_1D: $(1body_1D_THO_barrierws_OBJ)
	$(FC) -o $(BINPATH)/barrierws_1body_1D_THO  $(1body_1D_THO_barrierws_OBJ) $(LIBS) 
ht_THO_1body_1D: $(1body_1D_THO_ht_OBJ)
	$(FC) -o $(BINPATH)/ht_1body_1D_THO  $(1body_1D_THO_ht_OBJ) $(LIBS) 
pteller_THO_1body_1D: $(1body_1D_THO_pteller_OBJ)
	$(FC) -o $(BINPATH)/pteller_1body_1D_THO  $(1body_1D_THO_pteller_OBJ) $(LIBS) 
morse_THO_1body_1D: $(1body_1D_THO_morse_OBJ)
	$(FC) -o $(BINPATH)/morse_1body_1D_THO  $(1body_1D_THO_morse_OBJ) $(LIBS) 
ginocchio_THO_1body_1D: $(1body_1D_THO_ginocchio_OBJ)
	$(FC) -o $(BINPATH)/ginocchio_1body_1D_THO  $(1body_1D_THO_ginocchio_OBJ) $(LIBS) 
#######################
#######################
wsaxon_ISQW_1body_1D: $(1body_1D_ISQW_wsaxon_OBJ)
	$(FC) -o $(BINPATH)/wsaxon_1body_1D_ISQW  $(1body_1D_ISQW_wsaxon_OBJ) $(LIBS) 
ht_ISQW_1body_1D: $(1body_1D_ISQW_ht_OBJ)
	$(FC) -o $(BINPATH)/ht_1body_1D_ISQW  $(1body_1D_ISQW_ht_OBJ) $(LIBS) 
pteller_ISQW_1body_1D: $(1body_1D_ISQW_pteller_OBJ)
	$(FC) -o $(BINPATH)/pteller_1body_1D_ISQW  $(1body_1D_ISQW_pteller_OBJ) $(LIBS)
morse_ISQW_1body_1D: $(1body_1D_ISQW_morse_OBJ)
	$(FC) -o $(BINPATH)/morse_1body_1D_ISQW  $(1body_1D_ISQW_morse_OBJ) $(LIBS) 
ginocchio_ISQW_1body_1D: $(1body_1D_ISQW_ginocchio_OBJ)
	$(FC) -o $(BINPATH)/ginocchio_1body_1D_ISQW  $(1body_1D_ISQW_ginocchio_OBJ) $(LIBS) 
#######################
#######################
B1_B2_INTEGRAL: $(B1_B2_INTEGRAL_OBJ)
	$(FC) -o $(BINPATH)/B1_B2_INTEGRAL  $(B1_B2_INTEGRAL_OBJ) $(LIBS) 
#######################
clean:
	@rm -f $(1body_1D_HO_wsaxon_OBJ) $(1body_1D_HO_mexhat_OBJ)  $(1body_1D_HO_barrierws_OBJ)  $(1body_1D_HO_ht_OBJ) $(1body_1D_HO_pteller_OBJ) $(1body_1D_HO_morse_OBJ)  $(1body_1D_HO_ginocchio_OBJ)  $(1body_1D_THO_wsaxon_OBJ) $(1body_1D_THO_barrierws_OBJ)  $(1body_1D_THO_ht_OBJ) $(1body_1D_THO_pteller_OBJ) $(1body_1D_THO_morse_OBJ)  $(1body_1D_THO_ginocchio_OBJ)  $(1body_1D_ISQW_wsaxon_OBJ) $(1body_1D_ISQW_ht_OBJ)  $(1body_1D_ISQW_pteller_OBJ)  $(1body_1D_ISQW_morse_OBJ)  $(1body_1D_ISQW_ginocchio_OBJ)  $(B1_B2_INTEGRAL_OBJ)




