BINPATH = ../bin/
BINPATHINSTALL = /usr/local/bin
#
#     HO
1body_1D_HO_wsaxon_SRC = nrtype.f90 constants.f90 pot_param.f90	egs_mod_ho.f90 \
ho_1body_1D.f90 build_HO_bas.f90 ham_mat_1D_1body_ho.f90 \
wsaxon_pot.f90 e_gstate_ho.f90 e1_ho.f90 e2_ho.f90 \
wfp_ho.f90 total_strength.f90 ew_sum_rule.f90 \
phase_shift_HT.f90 phase_shift_CH.f90 
#
1body_1D_HO_wsaxon_OBJ = $(1body_1D_HO_wsaxon_SRC:.f90=.o)
#
1body_1D_HO_ht_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_ho.f90 \
ho_1body_1D.f90 build_HO_bas.f90 ham_mat_1D_1body_ho.f90 \
hazitaylor_pot.f90 e_gstate_ho.f90 e1_ho.f90 e2_ho.f90 \
wfp_ho.f90 total_strength.f90 ew_sum_rule.f90 \
phase_shift_HT.f90 phase_shift_CH.f90 
#
1body_1D_HO_ht_OBJ = $(1body_1D_HO_ht_SRC:.f90=.o)
#
1body_1D_HO_pt_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_ho.f90 \
ho_1body_1D.f90 build_HO_bas.f90 ham_mat_1D_1body_ho.f90 \
pteller_pot.f90 e_gstate_ho.f90 e1_ho.f90 e2_ho.f90 \
wfp_ho.f90 total_strength.f90 ew_sum_rule.f90 \
phase_shift_HT.f90 phase_shift_CH.f90 
#
1body_1D_HO_pt_OBJ = $(1body_1D_HO_pt_SRC:.f90=.o)
#
#
1body_1D_HO_morse_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_ho.f90 \
ho_1body_1D.f90 build_HO_bas.f90 ham_mat_1D_1body_ho.f90 \
morse_pot.f90 e_gstate_ho.f90 e1_ho.f90 e2_ho.f90 \
wfp_ho.f90 total_strength.f90 ew_sum_rule.f90 \
phase_shift_HT.f90 phase_shift_CH.f90 
#
1body_1D_HO_morse_OBJ = $(1body_1D_HO_morse_SRC:.f90=.o)
#
#
#     THO
1body_1D_THO_wsaxon_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_tho.f90 lst_param.f90 \
tho_1body_1D.f90 build_THO_bas.f90 ham_mat_1D_1body_tho.f90 e_gstate_tho.f90 \
wsaxon_pot.f90 wfp_tho.f90 total_strength.f90 ew_sum_rule.f90 \
e1_tho.f90 e2_tho.f90 phase_shift_HT.f90
1body_1D_THO_wsaxon_OBJ = $(1body_1D_THO_wsaxon_SRC:.f90=.o)
#
1body_1D_THO_pteller_SRC = nrtype.f90 constants.f90 pot_param.f90 egs_mod_tho.f90 lst_param.f90 \
tho_1body_1D.f90 build_THO_bas.f90 ham_mat_1D_1body_tho.f90 e_gstate_tho.f90 \
pteller_pot.f90 wfp_tho.f90 total_strength.f90 ew_sum_rule.f90 \
e1_tho.f90 e2_tho.f90 phase_shift_HT.f90
1body_1D_THO_pteller_OBJ = $(1body_1D_THO_pteller_SRC:.f90=.o)
#
#
#     ISQW
1body_1D_ISQW_wsaxon_SRC = nrtype.f90 constants.f90 pot_param.f90 \
egs_mod_isqw.f90 infsq_box_1D.f90 build_ISQW_bas.f90 ham_mat_1D_1body_isqw.f90 \
e1_isqw.f90 e2_isqw.f90 ew_sum_rule.f90 total_strength.f90 wsaxon_pot.f90 \
phase_shift_HT.f90
#
1body_1D_ISQW_wsaxon_OBJ = $(1body_1D_ISQW_wsaxon_SRC:.f90=.o)
#
1body_1D_ISQW_ht_SRC = nrtype.f90 constants.f90 pot_param.f90 \
egs_mod_isqw.f90 infsq_box_1D.f90 build_ISQW_bas.f90 ham_mat_1D_1body_isqw.f90 \
e1_isqw.f90 e2_isqw.f90 ew_sum_rule.f90 total_strength.f90 hazitaylor_pot.f90 \
phase_shift_HT.f90
#
1body_1D_ISQW_ht_OBJ = $(1body_1D_ISQW_ht_SRC:.f90=.o)
#
1body_1D_ISQW_pt_SRC = nrtype.f90 constants.f90 pot_param.f90 \
egs_mod_isqw.f90 infsq_box_1D.f90 build_ISQW_bas.f90 ham_mat_1D_1body_isqw.f90 \
e1_isqw.f90 e2_isqw.f90 ew_sum_rule.f90 total_strength.f90 pteller_pot.f90 \
phase_shift_HT.f90
#
1body_1D_ISQW_pt_OBJ = $(1body_1D_ISQW_pt_SRC:.f90=.o)
#
1body_1D_ISQW_morse_SRC = nrtype.f90 constants.f90 pot_param.f90 \
egs_mod_isqw.f90 infsq_box_1D.f90 build_ISQW_bas.f90 ham_mat_1D_1body_isqw.f90 \
e1_isqw.f90 e2_isqw.f90 ew_sum_rule.f90 total_strength.f90 morse_pot.f90 \
phase_shift_HT.f90
#
1body_1D_ISQW_morse_OBJ = $(1body_1D_ISQW_morse_SRC:.f90=.o)
#
#
FC = gfortran
FOPT	= -c 
FOPT   += -Wall
MODLIB   = -I/usr/local/lib/lapack95/lapack95_modules -I/usr/local/include/lapack95_modules
FOPT   += $(MODLIB)
#
# LAPACK95_PATH = /usr/local/lib/lapack95
LAPACK95 = -L/usr/local/lib/lapack95 -llapack95 -L/usr/local/lib -llapack95
# 
LAPACK77 = -llapack
BLAS     = -lblas
# NAG
NAGLIB = -L/usr/local/lib/NAG -lnag
#
LIBS     = $(NAGLIB) $(LAPACK95) $(LAPACK77) $(BLAS)

all: HO THO ISQW
all_static: HO_static THO_static ISQW_static
#
HO: wsaxon_HO_1body_1D ht_HO_1body_1D pt_HO_1body_1D morse_HO_1body_1D
HO_static: wsaxon_HO_1body_1D_static ht_HO_1body_1D_static pt_HO_1body_1D_static morse_HO_1body_1D_static
#
THO: wsaxon_THO_1body_1D pteller_THO_1body_1D
THO_static: wsaxon_THO_1body_1D_static pteller_THO_1body_1D_static
#
ISQW: wsaxon_ISQW_1body_1D ht_ISQW_1body_1D pteller_ISQW_1body_1D morse_ISQW_1body_1D
ISQW_static: wsaxon_ISQW_1body_1D_static ht_ISQW_1body_1D_static pteller_ISQW_1body_1D_static morse_ISQW_1body_1D_static
#
.PHONY : all
#
# Standard compilation rules
#
%.o: %.f90
	$(FC) $(FOPT) -c $<
#
%.o: %.F90
	$(FC) $(FOPT) -c $<
#
%.o: %.f
	$(FC) $(FOPT) $<
#
#######################
wsaxon_HO_1body_1D: $(1body_1D_HO_wsaxon_OBJ)
	$(FC) -o $(BINPATH)/wsaxon_1body_1D_HO  $(1body_1D_HO_wsaxon_OBJ) $(LIBS) 
ht_HO_1body_1D: $(1body_1D_HO_ht_OBJ)
	$(FC) -o $(BINPATH)/ht_1body_1D_HO  $(1body_1D_HO_ht_OBJ) $(LIBS) 
pt_HO_1body_1D: $(1body_1D_HO_pt_OBJ)
	$(FC) -o $(BINPATH)/pteller_1body_1D_HO  $(1body_1D_HO_pt_OBJ) $(LIBS) 
morse_HO_1body_1D: $(1body_1D_HO_morse_OBJ)
	$(FC) -o $(BINPATH)/morse_1body_1D_HO  $(1body_1D_HO_morse_OBJ) $(LIBS) 
#######################
wsaxon_HO_1body_1D_static: $(1body_1D_HO_wsaxon_OBJ)
	$(FC) -static -o $(BINPATH)/wsaxon_1body_1D_HO  $(1body_1D_HO_wsaxon_OBJ) $(LIBS) 
ht_HO_1body_1D_static: $(1body_1D_HO_ht_OBJ)
	$(FC) -static -o $(BINPATH)/ht_1body_1D_HO  $(1body_1D_HO_ht_OBJ) $(LIBS) 
pt_HO_1body_1D_static: $(1body_1D_HO_pt_OBJ)
	$(FC) -static -o $(BINPATH)/pteller_1body_1D_HO  $(1body_1D_HO_pt_OBJ) $(LIBS) 
morse_HO_1body_1D_static: $(1body_1D_HO_morse_OBJ)
	$(FC) -static -o $(BINPATH)/morse_1body_1D_HO  $(1body_1D_HO_morse_OBJ) $(LIBS) 
#######################
#######################
wsaxon_THO_1body_1D: $(1body_1D_THO_wsaxon_OBJ)
	$(FC) -o $(BINPATH)/wsaxon_1body_1D_THO  $(1body_1D_THO_wsaxon_OBJ) $(LIBS) 
pteller_THO_1body_1D: $(1body_1D_THO_pteller_OBJ)
	$(FC) -o $(BINPATH)/pteller_1body_1D_THO  $(1body_1D_THO_pteller_OBJ) $(LIBS) 
#######################
wsaxon_THO_1body_1D_static: $(1body_1D_THO_wsaxon_OBJ)
	$(FC) -static -o $(BINPATH)/wsaxon_1body_1D_THO  $(1body_1D_THO_wsaxon_OBJ) $(LIBS) 
pteller_THO_1body_1D_static: $(1body_1D_THO_pteller_OBJ)
	$(FC) -static -o $(BINPATH)/pteller_1body_1D_THO  $(1body_1D_THO_pteller_OBJ) $(LIBS) 
#######################
#######################
wsaxon_ISQW_1body_1D: $(1body_1D_ISQW_wsaxon_OBJ)
	$(FC) -o $(BINPATH)/wsaxon_1body_1D_ISQW  $(1body_1D_ISQW_wsaxon_OBJ) $(LIBS) 
ht_ISQW_1body_1D: $(1body_1D_ISQW_ht_OBJ)
	$(FC) -o $(BINPATH)/ht_1body_1D_ISQW  $(1body_1D_ISQW_ht_OBJ) $(LIBS) 
pteller_ISQW_1body_1D: $(1body_1D_ISQW_pt_OBJ)
	$(FC) -o $(BINPATH)/pteller_1body_1D_ISQW  $(1body_1D_ISQW_pt_OBJ) $(LIBS) 
morse_ISQW_1body_1D: $(1body_1D_ISQW_morse_OBJ)
	$(FC) -o $(BINPATH)/morse_1body_1D_ISQW  $(1body_1D_ISQW_morse_OBJ) $(LIBS) 
#######################
wsaxon_ISQW_1body_1D_static: $(1body_1D_ISQW_wsaxon_OBJ)
	$(FC) -static -o $(BINPATH)/wsaxon_1body_1D_ISQW  $(1body_1D_ISQW_wsaxon_OBJ) $(LIBS) 
ht_ISQW_1body_1D_static: $(1body_1D_ISQW_ht_OBJ)
	$(FC) -static -o $(BINPATH)/ht_1body_1D_ISQW  $(1body_1D_ISQW_ht_OBJ) $(LIBS) 
pteller_ISQW_1body_1D_static: $(1body_1D_ISQW_pt_OBJ)
	$(FC) -static -o $(BINPATH)/pteller_1body_1D_ISQW  $(1body_1D_ISQW_pt_OBJ) $(LIBS) 
morse_ISQW_1body_1D_static: $(1body_1D_ISQW_morse_OBJ)
	$(FC) -static -o $(BINPATH)/morse_1body_1D_ISQW  $(1body_1D_ISQW_morse_OBJ) $(LIBS) 
#######################
#######################
install:
	@cp $(BINPATH)/dBde_script $(BINPATH)/program_launcher_1body_N $(BINPATH)/morse_1body_1D_HO $(BINPATH)/pteller_1body_1D_HO $(BINPATH)/ht_1body_1D_HO $(BINPATH)/wsaxon_1body_1D_HO $(BINPATH)/wsaxon_1body_1D_THO $(BINPATH)/wsaxon_1body_1D_ISQW $(BINPATH)/ht_1body_1D_ISQW $(BINPATH)/pteller_1body_1D_ISQW $(BINPATH)/morse_1body_1D_ISQW $(BINPATH)/pteller_1body_1D_THO $(BINPATHINSTALL)
#######################
#######################
uninstall:
# 	@rm $(BINPATHINSTALL)/dBde_script $(BINPATHINSTALL)/program_launcher_1body_N $(BINPATHINSTALL)/morse_1body_1D_HO $(BINPATHINSTALL)/pteller_1body_1D_HO $(BINPATHINSTALL)/ht_1body_1D_HO $(BINPATHINSTALL)/wsaxon_1body_1D_HO $(BINPATHINSTALL)/wsaxon_1body_1D_THO $(BINPATHINSTALL)/wsaxon_1body_1D_ISQW $(BINPATHINSTALL)/ht_1body_1D_ISQW $(BINPATHINSTALL)/pteller_1body_1D_ISQW $(BINPATHINSTALL)/morse_1body_1D_ISQW $(BINPATHINSTALL)/pteller_1body_1D_THO 
# #######################
# #######################
clean:
	@rm -f $(1body_1D_HO_wsaxon_OBJ)  $(1body_1D_HO_ht_OBJ) $(1body_1D_THO_wsaxon_OBJ) $(1body_1D_ISQW_wsaxon_OBJ) $(1body_1D_ISQW_pt_OBJ) $(1body_1D_HO_morse_OBJ) *.mod




